Attribute VB_Name = "Mod_Prefs"
'######
'# Preferences Module for FunTalk 1.01
'# Written by Dodo2479@hotmail.com
'######
Option Explicit

Public Function CheckFile(Filepath As String) As Boolean
'A little function to checl if a file exists...
'USEAGE : If checkfile(app.path & "\Filename.ext") = true then.....
    If Dir(Filepath) = "" Then
        CheckFile = False
    Else
        CheckFile = True
    End If
End Function

'This function is to controll changes if the prefs.
'It's used by "OldPrf" and "NewPrf"
Public Function GetPrefs() As String
Dim gI As Integer, gVal(0 To 5) As String
With Frm_Prefs
        For gI = 0 To .Op_Rate.Count - 1
            If .Op_Rate(gI).Value = True Then gVal(0) = gI
        Next gI
    gI = Empty
        For gI = 0 To .Op_Bits.Count - 1
            If .Op_Bits(gI).Value = True Then gVal(1) = gI
        Next gI
    gI = Empty
        For gI = 0 To .Op_Chan.Count - 1
            If .Op_Chan(gI).Value = True Then gVal(2) = gI
        Next gI
    gI = Empty
    
gVal(3) = .CB_Pdev.List(.CB_Pdev.ListIndex)
gVal(4) = .CB_Cdev.List(.CB_Cdev.ListIndex)

'Set reminder string
GetPrefs = gVal(0) & "," & gVal(1) & "," & gVal(2) & "," & gVal(3) & "," & gVal(4)

'Get Sample rate
Select Case gVal(0)
    Case 0
        FRate = 44100
    Case 1
        FRate = 22050
    Case 2
        FRate = 11025
    Case 3
        FRate = 8000
End Select

'Get bitspersample
Select Case gVal(1)
    Case 0
        FBits = 8
    Case 1
        FBits = 16
End Select

'Get Channels
Select Case gVal(2)
    Case 0
        FChan = 1
    Case 1
        FChan = 2
End Select

'Get Playback device
FpDev = .CB_Pdev.ListIndex + 1
'Get Capture device
FcDev = .CB_Cdev.ListIndex + 1

End With
End Function

'To en- / Decode strings...
Public Function EnDeCo(edString As String, Encode As Boolean)
Dim edI As Integer, edN As String, edW As String
Select Case Encode
    Case True   'Text to Code
        For edI = 1 To Len(edString)
            edN$ = Asc(Mid(edString, edI, Len(edString))) + 120
            edW$ = edW$ & Chr(edN$)
        Next edI
        EnDeCo = edW$
        Exit Function
        
    Case False  'Code to Text
        For edI = 1 To Len(edString)
            edN$ = Asc(Mid(edString, edI, Len(edString))) - 120
            edW$ = edW$ & Chr(edN$)
        Next edI
        EnDeCo = edW$
        Exit Function
End Select
End Function

'For save the prefs. to a file
Public Function SavePrefs()
Dim Dstr() As String, D As String, X As Integer
'Retrieve Settings...
Dstr() = Split(GetPrefs, ",")
D = UBound(Dstr)

    'Delete old file if exists
    If CheckFile(FPref) = True Then Kill FPref
    
    'Open new file
    Open FPref For Output As #FL
        Print #FL, "#############################################"
        Print #FL, "#               FunTalk 1.01                #"
        Print #FL, "#                                           #"
        Print #FL, "#                 Written                   #"
        Print #FL, "#                    by                     #"
        Print #FL, "#            Dodo2479@hotmail.com           #"
        Print #FL, "#                                           #"
        Print #FL, "#############################################"
        Print #FL, "#                                           #"
        Print #FL, "#                WARNING :                  #"
        Print #FL, "#        DATA FILE FROM FUNTALK 1.01        #"
        Print #FL, "#          DO NOT EDIT THIS FILE            #"
        Print #FL, "#                                           #"
        Print #FL, "#############################################" & vbCrLf
        Print #FL, EnDeCo("<ST0>" & Dstr(0) & "," & Dstr(1) & "," & Dstr(2) & "<ST1>", True)
        Print #FL, EnDeCo("<PD0>" & Dstr(3) & "<PD1>", True)
        Print #FL, EnDeCo("<RD0>" & Dstr(4) & "<RD1>", True) & vbCrLf
        Print #FL, "#############################################"
        Print #FL, "#                                           #"
        Print #FL, "#               FunTalk 1.01                #"
        Print #FL, "#                                           #"
        Print #FL, "#############################################"
        
    Close #FL
    
    'Use them and set a new oldpref
    Call LoadPrefs
End Function


'For Loading the Settingsfile
Public Function LoadPrefs()
   Select Case CheckFile(FPref)
        Case False
            'Welcome....
            Frm_Splash.Visible = False 'only display the msgbox
            MsgBox "Welcome...." & vbCrLf & vbCrLf & "This is Funtalk 1.01" & vbCrLf & "A voice changer application written by : Dodo2479@hotmail.com" & vbCrLf & vbCrLf & "This is probable the first time you start Funtalk." & vbCrLf & "The default setting will be loaded," & vbCrLf & "Please take a look at the preferences" & vbCrLf & "And correct them if nessesary...", vbInformation, "Welcome..."
            Frm_Splash.Visible = True 'show the splash...

            'set default settings....
            With Frm_Prefs
                .CB_Pdev.ListIndex = 0
                .CB_Cdev.ListIndex = 0
                .Op_Rate(0).Value = True
                .Op_Bits(1).Value = True
                .Op_Chan(1).Value = True
            End With
            
            'Save them...
            Call SavePrefs
            
            'Load them...
            Call LoadPrefs
            Exit Function
            
        Case True 'the settinngs file exists.. load it
            Dim Tmpdata As String, fVal() As String, vI As Integer
            Open FPref For Input As #FL
                Do While Not EOF(FL)
                    Line Input #FL, Tmpdata
                        Select Case Left(Tmpdata, 5)
                            Case EnDeCo("<ST0>", True)
                                 fVal() = Split(Mid(EnDeCo(Tmpdata, False), 6, Len(Tmpdata) - 10), ",")
                                 Frm_Prefs.Op_Rate(fVal(0)).Value = True
                                 Frm_Prefs.Op_Bits(fVal(1)).Value = True
                                 Frm_Prefs.Op_Chan(fVal(2)).Value = True
                                
                            Case EnDeCo("<PD0>", True)
                                 For vI = 0 To Frm_Prefs.CB_Pdev.ListCount - 1
                                        'set the sound device (if still exists...)
                                        If Frm_Prefs.CB_Pdev.List(vI) = Mid(EnDeCo(Tmpdata, False), 6, Len(Tmpdata) - 10) Then
                                            Frm_Prefs.CB_Pdev.ListIndex = vI
                                        Else
                                            'if a saved sound device doesn't exists anymore set the sound
                                            'device to windows default...
                                            Frm_Prefs.CB_Pdev.ListIndex = 0
                                        End If
                                  Next vI
                                    vI = Empty
                            Case EnDeCo("<RD0>", True)
                                 For vI = 0 To Frm_Prefs.CB_Cdev.ListCount - 1
                                        'set the sound device (if still exists...)
                                        If Frm_Prefs.CB_Cdev.List(vI) = Mid(EnDeCo(Tmpdata, False), 6, Len(Tmpdata) - 10) Then
                                            Frm_Prefs.CB_Cdev.ListIndex = vI
                                        Else
                                            'if a saved sound device doesn't exists anymore set the sound
                                            'device to windows default...
                                            Frm_Prefs.CB_Cdev.ListIndex = 0
                                        End If
                                 Next vI
                                    vI = Empty
                        End Select
                   Loop
            Close #FL
    End Select

'set old preference string to controll changes in the settings form...
OldPrf = GetPrefs

End Function

